### PR TITLE
feat: HaiProxy Ownable2Step

### PR DESCRIPTION
**Pull request by 0xJabberwock**

### CODE REVIEW

**Review by wei3erHase — CHANGES_REQUESTED** [review]
this PR has more changes than the title implies, please update the branch and solve the conflicts 🙏

**Comment by xBA5ED** [comment]
Looks like something went wrong here, this PR should only be the last 2 commits. The other ones should have already been merged in the old PR 15 ([70110a4](https://github.com/defi-wonderland/hai-core/commit/70110a413a25c4ae5004c8e83f1b097a6aa982b4))

**Review by xBA5ED — APPROVED** [review]

**Review by wei3erHase — COMMENTED** [review]
it feels very weird to have to declare all this `super.` calls, can we make sure that there's no combination of inheritance that saves us some of this declarations? 🙏

**Comment by 0xJabberwock** [comment]
Based on my observations, `HaiOwnable2Step` needs to explicitly override each function due to its two base classes (`Ownable2Step` and `IHaiOwnable2Step`) being totally independent during linearization of inheritance; in fact, changing the order of inheritance does not influence at all. 🤨

Apparently, the functions in an interface cannot get overridden implicitly outside the colliding contract's scope.

On the other hand, how we inherit in `HaiProxy` does not seem to differ from how we do it in many other contracts of the repo. It may be that, once overrides are explicit, they are required to keep being it. 🤔

Further related discussion can be found in https://github.com/defi-wonderland/hai-core/pull/8#discussion_r1375302738.

**Comment by xBA5ED** [comment]
I came to the same conclusion, I tried a lot of orders of inheritance but always ended up with errors about needing to override them explicitly. Im not sure we way to get rid of these overrides without modifying `Ownable2Step` to add an interface to the contract.

**Review by wei3erHase — APPROVED** [review]
lgtm! 🚀

**Pull request merged**
