### PR TITLE
feat: HaiSafeManager simplification

### PR DESCRIPTION
**Pull request by 0xJabberwock**
Closes HAI-301

### CODE REVIEW

**Review by xBA5ED — DISMISSED** [review]
LGTM :ship:

**Comment by 0xGorilla** [comment]
Question by wei3er: Should we update something on the docs? @0xJabberwock

**Comment by 0xJabberwock** [comment]
> Question by wei3er: Should we update something on the docs? @0xJabberwock

Regarding the removed functions and their detailed documentation:
- I deleted the only line that explained the functionality of `enterSystem()`;
- no lines detailed the usability of `addSAFE()` or `removeSAFE()`.

Regarding the `openSAFE()` change and its documentation:
- NatSpec has been updated accordingly;
- no conflicts arose from its detailed documentation.

**Review by wei3erHase — COMMENTED** [review]
ok, let's wait for HAI confirmation

**Comment by wei3erHase** [comment]
closed as requested by HAI team

**Pull request closed without merging**
